### ISSUE TITLE
documentation.md

### ISSUE THREAD

**Issue by riggs** [AdvancedModularManikin/amm-tiny#2]
Then control flow discussion is impossible to follow without having code references to look at.

It looks like the chunk handling stuff exists both here and in spi_proto. Should the spi stuff here be moved into an `include` (or something) directory in spi_proto? Especially since they need to be version matched, anyway? Maybe have two `include`s, one for k66 & one for the Linux side?

In lieu of all that, put the chunk stuff in its own file (`spi_chunk.md`?) in `source` and remove this file.

**Comment by riggs** [comment]
I *think* most of the above also applies to `remote_api.md`, which seems to have some redundant info, and some additional context. Let's merge it all, if this is the case.

**Comment by peterohanley** [comment]
I moved the content, but I think the description of operation is worse now. I'll take another crack at it.
